boudicca:
    collector:
        collection-interval: PT24H
        collectors:
            -   type: ZeroxA
            -   type: alpenverein
            -   type: antonbrucknerunilinz
            -   type: arenawien
            -   type: brucknerhaus
            -   type: burgclam
            -   type: cafetraxlmayr
            -   type: chaosevents_clerie_de
            -   type: chelsea
            -   type: ennsevents
            -   type: events_ccc_de
            -   type: familienkarte
            -   type: femalecoder
            -   type: fhLUG
            -   type: flohmarkt
            -   type: fraeuleinflorentine
            -   type: fueruns
            -   type: jku
            -   type: kapu
            -   type: kunstunilinz
            -   type: kupfticket
            -   type: landestheaterlinz
            -   type: lastspace
            -   type: linztermine
            -   type: metalcorner
            -   type: museumArbeitswelt
            -   type: oehjku
            -   type: okhvoecklabruck
            -   type: ooesb
            -   type: otelolinz
            -   type: parlament
            -   type: planettt
            -   type: posthof
            -   type: roeda
            -   type: schlachthof
            -   type: spinnerei
            -   type: stadthallewien
            -   type: stadtwerkstatt
            -   type: stiftskonzerte
            -   type: tabakfabriklinz
            -   type: technologieplauscherl
            -   type: theaterinderinnenstadt
            -   type: theaterphoenix
            -   type: valug
            -   type: viperroom
            -   type: wissensturm
            -   type: zuckerfabrik
    monitoring:
        #for local testing uncomment line
        #endpoint: http://localhost:4318/v1/
        user: otlp
        password: otlp
spring:
    application:
        name: eventcollectors
    main:
        web-application-type: servlet

management:
    tracing:
        sampling:
            probability: 1
