#logging.level.ROOT: DEBUG
server.port=8080
boudicca.search.url=http://localhost:8082
boudicca.search.additionalFilter=
spring.devtools.restart.exclude=static/**,templates/**
spring.application.name=publisher-html
management.tracing.sampling.probability=1
boudicca.monitoring.tracing.endpoint=http://localhost:4318/v1/traces