include("eventcollector-api")
include("eventcollectors")
include("publisher-api")
include("publisher-ical")
include("publisher-html")
include("enricher")
include("enricher-openapi")
include("eventdb")
include("eventdb-openapi")
include("search")
include("search-openapi")
include("search-api")
include("semantic-conventions")

rootProject.name = "boudicca"