/*
 * Swagger with Quarkus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package at.cnoize.boudicca.api;

import at.cnoize.boudicca.invoker.ApiException;
import at.cnoize.boudicca.model.Event;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventResourcesApi
 */
@Disabled
public class EventResourcesApiTest {

    private final EventResourcesApi api = new EventResourcesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void eventGetTest() throws ApiException {
        Set<Event> response = api.eventGet();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void eventPostTest() throws ApiException {
        Event event = null;
        api.eventPost(event);
        // TODO: test validations
    }

}
