/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.cnoize.boudicca.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param startDate 
 * @param `data` 
 */


data class Event (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "startDate")
    val startDate: java.time.LocalDate,

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.String>

)

