name: Java CI with Gradle

on:
    push:
        branches: [ "main", "release/*" ]
    pull_request:
        branches: [ "main", "release/*" ]
    schedule:
        -   cron: "0 8 * * 2"

permissions:
    contents: read
    checks: write
    pull-requests: write

jobs:
    build-gradle-project:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    fetch-depth: 0
            -   name: Set up JDK 21
                uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Cache SonarQube packages
                uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Cache Playwright browsers
                uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
                with:
                    path: ~/.cache/ms-playwright
                    key: ${{ runner.os }}-playwright-${{ hashFiles('**/gradle/libs.versions.toml') }}
                    restore-keys: ${{ runner.os }}-playwright
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
            -   name: Execute Gradle build
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: ./gradlew build testCodeCoverageReport sonar --info
            -   name: Publish Test Report
                uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
                if: success() || failure() # always run even if the previous step fails
                with:
                    report_paths: '**/build/test-results/test/TEST-*.xml'
