name: Update Gradle Wrapper

on: workflow_dispatch # currently only on demand as maybe dependabot can update gradle wrapper now     

permissions: # this can be restrictive since there is a granular personal access token that is used to open the MergeRequest
    contents: read
    pull-requests: read

jobs:
    update-gradle-wrapper:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            -   name: Update Gradle Wrapper
                uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # 2.1.0
                with:
                    repo-token: ${{ secrets.YOLGIE_PAT_UPGRADE_GRADLEW_ACTION }}
                    pr-title-template: 'build(deps): Bump Gradle Wrapper from %sourceVersion% to %targetVersion%'
                    labels: dependencies
